#routes
home:
  path: /
  defaults: { _controller: mp.jobb.controller.category:index , format: html }


job_post:
  path: /jobs/create
  defaults: { _controller: mp.jobb.controller.job:create ,format:html }
  methods: [GET,POST]

job:
  prefix: /job
  resource: job.yml

category:
  prefix: /category
  resource: category.yml


admin_job:
  prefix: /admin/job
  resource: admin_job.yml

admin_category:
  prefix: /admin/category
  resource: admin_category.yml

admin_affiliate:
  prefix:  /admin/affiliate
  resource: admin_affiliate.yml
