#routes
home:
  path: /
  defaults: { _controller: mp.jobb.controller.category:index , format: html }

job_principe:
  path: /jobs
  defaults: { _controller: mp.jobb.controller.job:index  ,format: html }

job_detail:
  path: /jobs/{company}/{location}/{id}/{position}
  defaults: { _controller: mp.jobb.controller.job:read }
  methods: [GET]
  requirements:
    id: \d+

job_post:
  path: /jobs/create
  defaults: { _controller: mp.jobb.controller.job:create ,format:html }
  methods: [GET,POST]


category:
  prefix: /category
  resource: category.yml


admin_job:
  prefix: /admin/job
  resource: admin_job.yml
